[package]
name = "wasm-layer-system"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
thiserror = "1.0"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Document",
    "Element",
    "HtmlElement",
    "MouseEvent",
    "EventTarget",
    "Window",
    "Node",
    "DomTokenList",
    "CssStyleDeclaration",
    "DomRect",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
